---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: spring-commons-github

outputs:
- name: spring-commons-artifactory

caches:
- path: maven

run:
  path: spring-commons-github/ci/build.sh
